import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    // bindings.ts is generated by `cargo test -p mast-desktop` (tauri-specta).
    // fixtures/ hold byte-exact test material (compose-corpus traps CRLF,
    // missing trailing newlines, etc.) — formatters must NEVER touch them.
    ignorePatterns: ["**/src/bindings.ts", "fixtures/**"],
  },
  lint: {
    // bindings.ts is generated; the fallback config deliberately imports
    // vanilla vitest (it exists to escape vite-plus — see plan §9).
    ignorePatterns: ["**/src/bindings.ts", "**/vite.config.fallback.ts", "fixtures/**"],
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
  },
});
