// @ts-nocheck — generated by tauri-specta; do not edit

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async snapshot() : Promise<Result<EngineSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start (or replace) the patch subscription. Items arrive as
 * [`PatchStreamItem`] events tagged with `stream_id`.
 */
async startPatchStream(streamId: number, afterSeq: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_patch_stream", { streamId, afterSeq }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dispatch any action; the operation's full event history (replayed from the
 * first event) streams over `on_event` until a terminal event.
 */
async dispatchAction(action: Action, onEvent: TAURI_CHANNEL<OperationEvent>) : Promise<Result<OperationId, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_action", { action, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOperation(id: OperationId) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_operation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async envReport(project: ProjectId) : Promise<Result<EnvReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("env_report", { project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async laravelLog(project: ProjectId) : Promise<Result<LaravelLogReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("laravel_log", { project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async networkAttachPreview(workspace: WorkspaceId, project: ProjectId) : Promise<Result<FileEditPreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("network_attach_preview", { workspace, project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSnapshots(workspace: WorkspaceId) : Promise<Result<WorkspaceSnapshot[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_snapshots", { workspace }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async snapshotReport(snapshotId: string) : Promise<Result<SnapshotReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("snapshot_report", { snapshotId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runDiagnostics() : Promise<Result<DiagnosticReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_diagnostics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async repairPreview(repair: string, arg: string | null, project: ProjectId | null) : Promise<Result<RepairPlan, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("repair_preview", { repair, arg, project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async diagnosticsHistory() : Promise<Result<DiagnosticsHistory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("diagnostics_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async catalog(project: ProjectId) : Promise<Result<CatalogEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("catalog", { project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async catalogPreview(project: ProjectId, service: string, remove: boolean) : Promise<Result<FileEditPreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("catalog_preview", { project, service, remove }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async serviceRemovePreview(project: ProjectId, service: string) : Promise<Result<FileEditPreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("service_remove_preview", { project, service }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async serviceImagePreview(project: ProjectId, service: string, image: string) : Promise<Result<FileEditPreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("service_image_preview", { project, service, image }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async customServicePreview(project: ProjectId, spec: CustomServiceSpec) : Promise<Result<FileEditPreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("custom_service_preview", { project, spec }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Follow a service's container logs over a dedicated channel (plan §3: log
 * streams bypass the patch store). Returns a handle for `stop_log_stream`.
 */
async streamServiceLogs(project: ProjectId, service: string, tail: number, onLine: TAURI_CHANNEL<LogLine>) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_service_logs", { project, service, tail, onLine }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopLogStream(handle: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_log_stream", { handle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The effect-history backlog (M9): what Mast has run and written, oldest
 * first. Fetched once at connect; [`start_history_stream`] keeps it current.
 */
async historyRecent() : Promise<Result<HistoryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("history_recent") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Follow effect history. Entries arrive on creation and again on completion;
 * the frontend upserts by id. Replaces any earlier subscription.
 */
async startHistoryStream(onEntry: TAURI_CHANNEL<HistoryEntry>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_history_stream", { onEntry }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stored log captures (M10), newest first: what each container was saying
 * just before it went down. Read from disk, so this survives an app restart.
 */
async logCaptures(limit: number) : Promise<Result<LogCapture[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_captures", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Follow log captures. Append-only — the frontend prepends. Replaces any
 * earlier subscription.
 */
async startCaptureStream(onCapture: TAURI_CHANNEL<LogCapture>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_capture_stream", { onCapture }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Follow live CPU/memory usage (M11). **Calling this is what starts the
 * engine sampling** — it makes no docker calls while nobody is subscribed, so
 * the frontend stops the stream whenever the window is hidden. Replaces any
 * earlier subscription.
 */
async startUsageStream(onSample: TAURI_CHANNEL<UsageSample>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_usage_stream", { onSample }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drop the usage subscription, which stops the engine sampling.
 */
async stopUsageStream() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_usage_stream") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
patchStreamItem: PatchStreamItem
}>({
patchStreamItem: "patch-stream-item"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Client-initiated mutations. Every dispatch yields an [`OperationId`] whose
 * lifecycle is streamed as [`OperationEvent`]s — no fire-and-forget.
 */
export type Action = 
/**
 * Exercises the operation machinery (progress/cancel) without touching
 * state. Kept for protocol tests and demos.
 */
{ type: "startFakeOperation"; project: ProjectId } | { type: "importProject"; path: string } | { type: "removeProject"; id: ProjectId } | { type: "addWatchedDirectory"; path: string } | { type: "removeWatchedDirectory"; path: string } | 
/**
 * `up -d` via the project's runner (sail or compose), terminal parity.
 */
{ type: "startProject"; id: ProjectId } | 
/**
 * Per-service lifecycle: `up -d <service>` / `stop <service>` /
 * `restart <service>` (compose and sail both accept trailing services).
 */
{ type: "startService"; id: ProjectId; service: string } | { type: "stopService"; id: ProjectId; service: string } | { type: "restartService"; id: ProjectId; service: string } | 
/**
 * `stop` via the project's runner.
 */
{ type: "stopProject"; id: ProjectId } | 
/**
 * `restart` via the project's runner.
 */
{ type: "restartProject"; id: ProjectId } | 
/**
 * Open the configured (or auto-detected) terminal at the project root.
 */
{ type: "openTerminal"; id: ProjectId } | 
/**
 * Open a terminal running an interactive shell inside the service's
 * container.
 */
{ type: "shellIntoContainer"; id: ProjectId; service: string } | 
/**
 * Open the project in the configured (or auto-detected) editor.
 */
{ type: "openInEditor"; id: ProjectId } | 
/**
 * Reveal the project directory in the system file manager.
 */
{ type: "revealInFileManager"; id: ProjectId } | 
/**
 * Open the project's `.env` address (`ProjectSummary::app_url`) in the
 * default browser.
 */
{ type: "openInBrowser"; id: ProjectId } | 
/**
 * Open an http(s) URL Mast itself surfaced (share URL, tunnel
 * dashboard) in the default browser. Non-http schemes are refused.
 */
{ type: "openUrl"; url: string } | 
/**
 * Persist external-tool preferences.
 */
{ type: "setIntegrations"; integrations: IntegrationSettings } | 
/**
 * Set a LITERAL value in the project's .env (lossless model; creates
 * the file if absent).
 */
{ type: "setEnvVar"; id: ProjectId; key: string; value: string } | 
/**
 * Remove a key from the project's .env.
 */
{ type: "removeEnvVar"; id: ProjectId; key: string } | 
/**
 * Create or replace a workspace definition (matched by id when present).
 */
{ type: "saveWorkspace"; id: WorkspaceId | null; name: string; members: WorkspaceMember[] } | { type: "removeWorkspace"; id: WorkspaceId } | 
/**
 * Start all members in dependency order, waiting for readiness between
 * layers; a failing member blocks its dependents.
 */
{ type: "startWorkspace"; id: WorkspaceId } | 
/**
 * Stop all members in reverse dependency order.
 */
{ type: "stopWorkspace"; id: WorkspaceId } | 
/**
 * Attach a member project's services to the workspace's shared
 * `mast-{slug}` network via the compose write transaction (preview
 * first with `network_attach_preview`).
 */
{ type: "attachNetwork"; workspace: WorkspaceId; project: ProjectId } | 
/**
 * Capture git refs + config hashes for every member (metadata only).
 */
{ type: "takeSnapshot"; workspace: WorkspaceId; name: string } | { type: "removeSnapshot"; id: string } | 
/**
 * Apply a previewed diagnostic repair. `repair`/`arg` come from a
 * [`RepairOffer`]; high-risk repairs require explicit consent in the UI.
 */
{ type: "applyRepair"; repair: string; arg: string | null; project: ProjectId | null } | 
/**
 * Add a catalog service to the project's compose file (previewed,
 * transactional) plus its documented `.env` updates.
 */
{ type: "addCatalogService"; id: ProjectId; service: string } | 
/**
 * Three-way removal: refused if the service block was customized after
 * it was added.
 */
{ type: "removeCatalogService"; id: ProjectId; service: string } | 
/**
 * Remove ANY service by its compose key, as-is (previewed; no three-way
 * baseline — for services Mast did not add).
 */
{ type: "removeService"; id: ProjectId; service: string } | 
/**
 * Add a user-described service (previewed transactional compose edit).
 */
{ type: "addCustomService"; id: ProjectId; spec: CustomServiceSpec } | 
/**
 * Retag a service's image — the whole of "change the MySQL version"
 * (previewed transactional compose edit). The container keeps running the
 * old image until a [`Action::RebuildService`].
 */
{ type: "setServiceImage"; id: ProjectId; service: string; image: string } | 
/**
 * Pull the service's image and recreate just that container, so a retag
 * (or any edited service block) takes effect.
 */
{ type: "rebuildService"; id: ProjectId; service: string } | 
/**
 * Switch a Sail-built service to another vendored PHP runtime, as ONE
 * operation: rewrites `build.context` and the `sail-X.Y/app` image tag
 * together, rebuilds without cache, recreates the container when the
 * project is running, and verifies `php -v` inside it — the exact
 * sequence users half-do by hand (laravel/sail#442).
 */
{ type: "setPhpVersion"; id: ProjectId; service: string; series: string } | 
/**
 * Pin the app's Node major (`build.args.NODE_VERSION`, Sail's
 * documented override of the runtime Dockerfile's default) and run the
 * same verified switch as PHP: rebuild without cache, recreate when
 * running, confirm `node -v` inside the container.
 */
{ type: "setNodeVersion"; id: ProjectId; service: string; major: string } | 
/**
 * Publish the running app through Sail's expose tunnel (`sail share`,
 * same image, flags and `.env` knobs). Long-running: the operation
 * stays live while the tunnel is up, cancelling it stops the share.
 * The public URL lands on [`ProjectSummary::share_url`] once the
 * tunnel reports it.
 */
{ type: "shareProject"; id: ProjectId } | 
/**
 * Claim (or clear, with `domain: None`) a stable `https://…test`
 * address for this project. Mast keeps one shared Caddy container
 * (`mast-proxy`, ports 80/443) whose internal CA signs the
 * certificate; the two host-side steps it cannot do silently — the
 * `/etc/hosts` line and trusting that CA — surface as high-risk Fix
 * buttons on the operation.
 */
{ type: "setLocalDomain"; id: ProjectId; domain: string | null } | 
/**
 * New-project wizard (M7): the documented Sail install — composer
 * create-project, `composer require laravel/sail --dev`, then `php artisan
 * sail:install --php=…` — each run in the official composer image inside
 * `parent`, then import the result. `php` is the series ("85"); `services`
 * empty = Sail's defaults.
 */
{ type: "createProject"; parent: string; name: string; php: string; services: string[] } | 
/**
 * Start a Laravel app process (`php artisan …` in the app container) as
 * a streamed cancellable operation.
 */
{ type: "startProcess"; id: ProjectId; process: string } | 
/**
 * Stop a Laravel app process (SIGTERM by cmdline match in-container —
 * also catches processes started from a terminal).
 */
{ type: "stopProcess"; id: ProjectId; process: string } | 
/**
 * Replace the project's user-defined command list (persisted).
 */
{ type: "setProjectCommands"; id: ProjectId; commands: ProjectCommand[] } | 
/**
 * Run one user-defined command as a streamed cancellable operation.
 */
{ type: "runProjectCommand"; id: ProjectId; name: string } | 
/**
 * Trigger an immediate discovery + observation reconcile.
 */
{ type: "refreshNow" } | 
/**
 * Capture a service's recent output now, without stopping anything.
 */
{ type: "captureServiceLogs"; id: ProjectId; service: string } | 
/**
 * Delete every stored log capture.
 */
{ type: "clearLogCaptures" }
/**
 * Why a capture was taken. The reason is the whole diagnostic frame: the same
 * forty lines mean something different before a user-requested restart than
 * they do after a container fell over on its own.
 */
export type CaptureReason = 
/**
 * Mast is about to stop/restart/rebuild this container. Taken *before*
 * the command, because a recreate removes the container and its log.
 */
{ type: "teardown"; verb: string } | 
/**
 * Observed to have exited without Mast asking. `status` is `None` when
 * the daemon did not report a code.
 */
{ type: "exited"; status: number | null } | 
/**
 * Observed to have gone unhealthy.
 */
{ type: "unhealthy" } | 
/**
 * A workspace start gave up waiting for this service to become ready.
 */
{ type: "readyTimeout" } | 
/**
 * The user asked for it from the service menu.
 */
{ type: "manual" }
/**
 * One installable companion service (Redis, Mailpit, …). `installed` means
 * the project already runs this software (matched by service key OR image,
 * however the user named the service); `removable` means the service key is
 * ours, so three-way removal can be offered.
 */
export type CatalogEntry = { id: string; title: string; description: string; installed: boolean; removable: boolean; 
/**
 * The compose service key that provides this software (ours or the
 * user's own name) — the target for generic removal when `removable`
 * is false.
 */
installedService: string | null; 
/**
 * When not installed but another service already fills the same role
 * (e.g. rustfs covers object storage), the image that covers it —
 * adding both usually conflicts on ports/env.
 */
roleCoveredBy: string | null; 
/**
 * The image this service currently runs, when installed — the value a
 * retag rewrites.
 */
installedImage: string | null; 
/**
 * Tags offered for `installed_image`'s repo, newest first, and always
 * including the tag it currently runs. Read from the registry and cached;
 * empty when the repo publishes no version-shaped tags, lives on a
 * registry Mast cannot query, or offers nothing but what is already
 * running — in each case there is no choice to present.
 */
versions: string[] }
/**
 * Container runtime state as reported by the daemon.
 */
export type ContainerState = "created" | "running" | "restarting" | "paused" | "exited" | "dead" | "removing" | "unknown"
/**
 * A user-described service for the compose file: the minimal shape people
 * add by hand — image, host ports, one data volume, a command.
 */
export type CustomServiceSpec = { name: string; image: string; ports?: string[]; 
/**
 * Container path persisted into a named volume `{name}-data`.
 */
volume?: string | null; command?: string | null }
export type DiagSeverity = "info" | "warning" | "error"
export type DiagnosticFinding = { check: string; severity: DiagSeverity; title: string; detail: string; project: ProjectId | null; projectName: string | null; repair: RepairOffer | null }
/**
 * Result of one diagnostics pass. No findings + `checks_run > 0` means
 * everything passed.
 */
export type DiagnosticReport = { takenUnix: number; checksRun: number; findings: DiagnosticFinding[] }
export type DiagnosticRunSummary = { id: number; takenUnix: number; checksRun: number; errors: number; warnings: number; infos: number }
export type DiagnosticsHistory = { runs: DiagnosticRunSummary[]; repairs: RepairAuditEntry[] }
/**
 * A candidate found under a watched directory, not yet imported.
 */
export type DiscoveredProject = { path: string; name: string; isSail: boolean }
export type DockerStatus = { available: boolean; contextName: string | null; endpoint: string | null; error: string | null }
/**
 * One minimal typed state change. `seq` values are contiguous per engine;
 * a gap observed by a client means it must resynchronize via snapshot.
 */
export type EnginePatch = { seq: number; event: PatchEvent }
/**
 * Consistent point-in-time view of engine state, tagged with the sequence
 * number of the last patch folded into it.
 */
export type EngineSnapshot = { protocolVersion: number; seq: number; 
/**
 * True when another Mast instance owns mutation on this machine; this
 * engine observes but refuses mutating actions (plan §1).
 */
readOnly: boolean; docker: DockerStatus; integrations: IntegrationSettings; watchedDirectories: string[]; discovered: DiscoveredProject[]; projects: ProjectSummary[]; workspaces: WorkspaceSummary[] }
export type EnvEntryView = { key: string; 
/**
 * Decoded value (interpolation left raw). The UI masks when `secret`.
 */
value: string; 
/**
 * Key matches the secret patterns (same set the redactor uses).
 */
secret: boolean; inExample: boolean }
export type EnvFinding = { severity: FindingSeverity; 
/**
 * The key the finding is about, when key-specific.
 */
key: string | null; message: string }
/**
 * On-demand env editor payload (never part of snapshots/patches — values
 * may be secrets and stay off the patch store).
 */
export type EnvReport = { envExists: boolean; exampleExists: boolean; entries: EnvEntryView[]; 
/**
 * Keys present in .env.example but missing from .env.
 */
missingFromEnv: string[]; findings: EnvFinding[] }
/**
 * A previewable config edit: whole-file before/after plus a human summary.
 * (Compose files are small; clients render their own diff.)
 */
export type FileEditPreview = { file: string; before: string; after: string; summary: string[]; 
/**
 * Nothing to do — already in the desired state.
 */
noOp: boolean }
export type FindingSeverity = "warning" | "error"
/**
 * What Mast actually did. Not every effect is a subprocess — config writes
 * change the developer's machine too, and a history that omitted them would
 * misrepresent what Mast had done.
 */
export type HistoryDetail = { type: "command"; argv: string[]; cwd: string | null; env: HistoryEnvVar[]; streaming: boolean } | { type: "fileWrite"; path: string; summary: string[] }
/**
 * One recorded effect. Redacted at construction: argv, env, and output have
 * already had known `.env` secrets removed.
 */
export type HistoryEntry = { 
/**
 * Monotonic per engine; identifies the entry an update replaces.
 */
id: number; atUnixMs: number; 
/**
 * What the user asked for ("Start acme-app"), not the argv.
 */
label: string; project: ProjectId | null; 
/**
 * The operation this effect belongs to, when it has one — lets a failed
 * operation link straight to the command behind it.
 */
operation: OperationId | null; origin: HistoryOrigin; detail: HistoryDetail; outcome: HistoryOutcome; durationMs: number | null; 
/**
 * Last lines of output, redacted; empty while still running.
 */
output: string[] }
/**
 * One env-overlay entry as recorded. Secret-looking keys carry a mask, never
 * the value — history is copyable, and a copy button must not hand out
 * credentials.
 */
export type HistoryEnvVar = { key: string; value: string; masked: boolean }
/**
 * Why an effect happened: something the user asked for, or Mast's own upkeep
 * (reconciliation, readiness probes, invocation resolution). Clients default
 * to showing only `User` — background traffic is constant and would bury it.
 */
export type HistoryOrigin = "user" | "background"
export type HistoryOutcome = 
/**
 * Still going. Streamed commands can sit here for a long time.
 */
{ type: "running" } | { type: "exited"; status: number } | { type: "cancelled" } | 
/**
 * Never produced a status: spawn failure, timeout, or a rejected write.
 */
{ type: "failed"; error: string } | 
/**
 * Launched detached (terminal, editor, browser) — outcome unknowable.
 */
{ type: "detached" } | 
/**
 * A file write that went through.
 */
{ type: "applied" }
/**
 * User preferences: which external tools to launch (M4 integrations, `None`
 * = auto-detect) and how Mast should behave on the user's behalf.
 */
export type IntegrationSettings = { 
/**
 * Terminal emulator binary (e.g. "ghostty", "kitty", "gnome-terminal");
 * on macOS also an app bundle ("Terminal.app").
 */
terminal: string | null; 
/**
 * Editor binary (e.g. "code", "zed").
 */
editor: string | null; 
/**
 * Move a published host port into `.env` when something else already
 * holds it, instead of letting `up` fail on the bind. Defaults on.
 */
autoPortRemap?: boolean }
/**
 * One grouped entry from `storage/logs/laravel.log`: the Monolog header
 * split into fields, with the stack trace (when one follows) kept attached
 * instead of scattered across raw lines.
 */
export type LaravelLogEntry = { timestamp: string; environment: string; 
/**
 * Monolog level, uppercase (`ERROR`, `WARNING`, …).
 */
level: string; message: string; 
/**
 * Continuation lines — stack trace, previous exceptions — when any.
 */
detail: string | null }
/**
 * The tail of the application log, parsed. On demand only, like
 * [`EnvReport`]: log bodies routinely carry user data.
 */
export type LaravelLogReport = { 
/**
 * False when `storage/logs/laravel.log` does not exist (fresh app, or
 * LOG_CHANNEL points elsewhere).
 */
exists: boolean; 
/**
 * Newest first.
 */
entries: LaravelLogEntry[]; 
/**
 * True when the file outgrew the read window and older entries were
 * left behind.
 */
truncated: boolean }
/**
 * A container's last words. Persisted, therefore redacted at write time —
 * unlike a live log stream, which is transient and is not (see `redact.rs`).
 */
export type LogCapture = { 
/**
 * Row id, ascending. Clients upsert by it.
 */
id: number; atUnixMs: number; project: ProjectId; 
/**
 * Denormalized so a capture stays readable after the project is removed.
 */
projectName: string; service: string; containerId: string; reason: CaptureReason; 
/**
 * How far back the read reached, in seconds.
 */
windowSecs: number; lines: LogCaptureLine[]; 
/**
 * The window held more lines than the cap; the oldest were dropped.
 */
truncated: boolean }
/**
 * One captured line. Carries Docker's own timestamp rather than an arrival
 * order, because a capture is read after the fact.
 */
export type LogCaptureLine = { 
/**
 * Docker's RFC3339 stamp, verbatim; `None` if the line had none.
 */
at: string | null; message: string; stderr: boolean }
/**
 * One line of a container log stream (delivered over a dedicated channel,
 * never through the patch store — plan §3 transport split).
 */
export type LogLine = { service: string; message: string; stderr: boolean }
export type OperationEvent = { operation: OperationId; kind: OperationEventKind }
export type OperationEventKind = { type: "started" } | { type: "progress"; percent: number; message: string } | 
/**
 * One line of live subprocess output (compose/sail shell-outs).
 */
{ type: "output"; line: string; stderr: boolean } | 
/**
 * A one-click repair that addresses a failure signature spotted in this
 * operation's output — emitted just before [`Self::Failed`], so a
 * failure can carry its own Fix button. Preview the repair before
 * applying; the preview says exactly what will change.
 */
{ type: "fixAvailable"; repair: RepairOffer; project: ProjectId } | { type: "completed" } | { type: "failed"; error: string } | { type: "cancelled" }
export type OperationId = number
export type PatchEvent = { type: "projectAdded"; project: ProjectSummary } | 
/**
 * Full-project replacement when observation/resolution changed anything
 * beyond bare status. Still a minimal patch at project granularity.
 */
{ type: "projectUpdated"; project: ProjectSummary } | { type: "projectStatusChanged"; id: ProjectId; status: ProjectStatus } | { type: "projectRemoved"; id: ProjectId } | { type: "discoveryChanged"; discovered: DiscoveredProject[] } | { type: "watchedDirectoriesChanged"; directories: string[] } | { type: "dockerStatusChanged"; status: DockerStatus } | { type: "integrationsChanged"; integrations: IntegrationSettings } | { type: "workspacesChanged"; workspaces: WorkspaceSummary[] }
/**
 * Global event carrying patch-stream items. `stream_id` lets the frontend
 * discard stragglers from a superseded subscription generation.
 */
export type PatchStreamItem = { streamId: number; item: SubscriptionItem }
/**
 * The app's Sail PHP runtime: what `build.context` currently pins and which
 * vendored runtimes it could switch to (drives the PHP version picker).
 */
export type PhpVersionInfo = { 
/**
 * The Sail-built compose service (usually the app).
 */
service: string; 
/**
 * PHP series the build context pins ("8.4").
 */
current: string; 
/**
 * Series available under `vendor/laravel/sail/runtimes/`.
 */
available: string[]; 
/**
 * Effective Node major: the compose `build.args.NODE_VERSION` override
 * when present, else the runtime Dockerfile's `ARG NODE_VERSION`
 * default. None when neither is readable.
 */
node?: string | null; 
/**
 * Node majors the picker offers (nodesource release lines the runtime
 * Dockerfile can install). Empty when the build shape cannot take an
 * override — the chip stays read-only then.
 */
nodeAvailable?: string[] }
/**
 * A Laravel app process (Reverb, Horizon, queue worker, scheduler): a
 * long-running artisan command inside the app container. Detected from
 * composer.json/.env; `running` comes from an in-container cmdline scan.
 */
export type ProcessState = { id: string; title: string; running: boolean }
/**
 * A user-defined per-project command (M7.5): argv-only (whitespace-split,
 * no shell), `sail` prefix resolves to `vendor/bin/sail`.
 */
export type ProjectCommand = { name: string; command: string; 
/**
 * Run automatically once the project reaches Running.
 */
autoStart: boolean }
export type ProjectId = string
export type ProjectStatus = "stopped" | "starting" | "running" | "degraded" | "failed"
export type ProjectSummary = { id: ProjectId; name: string; 
/**
 * Canonical project root path, rendered as a string for the wire.
 */
path: string; status: ProjectStatus; 
/**
 * Resolved compose project name (container↔project association key).
 */
composeProjectName: string | null; isSail: boolean; services: ServiceState[]; 
/**
 * Set when invocation/model resolution fails (e.g. compose file deleted);
 * the project stays listed and degrades gracefully.
 */
resolutionError: string | null; 
/**
 * User-defined commands (M7.5), persisted per project.
 */
commands?: ProjectCommand[]; 
/**
 * Laravel app processes (Reverb/Horizon/…) relevant to this project.
 */
processes?: ProcessState[]; 
/**
 * Current git branch ("detached" when headless); None outside a repo.
 */
gitBranch?: string | null; 
/**
 * Working tree has uncommitted changes; None outside a repo.
 */
gitDirty?: boolean | null; 
/**
 * Where the app answers in a browser, from `.env` (`APP_URL` plus
 * `APP_PORT`); None when `.env` gives no http(s) address.
 */
appUrl?: string | null; 
/**
 * The Sail PHP runtime and its alternatives; None when no service
 * builds from a Sail runtime shape.
 */
php?: PhpVersionInfo | null; 
/**
 * Public URL of the live share tunnel ([`Action::ShareProject`]);
 * None while not sharing.
 */
shareUrl?: string | null; 
/**
 * The live tunnel's local dashboard (SAIL_SHARE_DASHBOARD, possibly
 * auto-moved off a busy port); None while not sharing.
 */
shareDashboardUrl?: string | null; 
/**
 * Stable local HTTPS address ([`Action::SetLocalDomain`]) served by the
 * shared `mast-proxy` Caddy container; None when not claimed.
 */
localDomain?: string | null; 
/**
 * Non-fatal conditions worth surfacing (M4): unbootstrapped Sail clone,
 * missing .env, both compose-file families present, …
 */
warnings: string[] }
export type RepairAuditEntry = { appliedUnix: number; repair: string; projectName: string | null; risk: string; outcome: string }
/**
 * A repair a finding offers. `arg` disambiguates the target when the id
 * alone is not enough (e.g. which network to create).
 */
export type RepairOffer = { id: string; title: string; risk: RepairRisk; description: string; arg: string | null }
/**
 * What a repair will do, shown before consent. Env-file repairs carry a
 * full before/after preview; command repairs describe their argv.
 */
export type RepairPlan = { repair: RepairOffer; summary: string[]; filePreview: FileEditPreview | null; 
/**
 * Already in the desired state.
 */
noOp: boolean }
export type RepairRisk = 
/**
 * Reversible, project-local (env edit, file copy).
 */
"safe" | 
/**
 * Runs containers or touches docker resources.
 */
"caution" | 
/**
 * Elevation or group membership — explicit consent UI required.
 */
"highRisk"
export type ServiceHealth = "unknown" | "starting" | "healthy" | "unhealthy"
/**
 * One compose service of a project: declared by the resolved model and/or
 * observed as a container. `container_id == None` means declared-but-absent.
 */
export type ServiceState = { name: string; containerId: string | null; state: ContainerState | null; health: ServiceHealth; 
/**
 * Host-reachable address of this service's web dashboard (Mailpit,
 * Meilisearch, MinIO console, …) when the image is recognized and the
 * container port is published — powers "Open UI" on the service chip.
 */
uiUrl?: string | null; 
/**
 * Host-side port of a recognized database service — what a GUI client
 * on the host connects to (with the credentials from `.env`).
 */
dbPort?: number | null }
/**
 * One service's share of the machine, over one sampling interval.
 */
export type ServiceUsage = { project: ProjectId; service: string; 
/**
 * Cores consumed over the interval: `1.0` is one saturated core. Cores
 * rather than a percentage because Docker's percentage is of *all* cores
 * — 800% is reachable on an 8-core box, so a 0–100 reading misleads.
 */
cpuCores: number; 
/**
 * Working set: page cache excluded, as `docker stats` reports it. Raw
 * cgroup usage counts reclaimable cache and overstates badly.
 */
memoryBytes: number; memoryLimitBytes: number; 
/**
 * Whether `memory_limit_bytes` is a real cgroup limit rather than just
 * host RAM. This is the difference between "using a third of this
 * machine" and "a third of the way to being OOM-killed".
 */
memoryLimited: boolean }
export type SnapshotDelta = { projectName: string; changes: string[] }
export type SnapshotFileHash = { path: string; sha256: string }
export type SnapshotMemberState = { project: ProjectId; projectName: string; gitBranch: string | null; gitCommit: string | null; gitDirty: boolean | null; 
/**
 * Compose files + .env at capture time.
 */
fileHashes: SnapshotFileHash[] }
/**
 * Current state vs a snapshot, as a human report (restore is a report,
 * never an automatic apply).
 */
export type SnapshotReport = { snapshot: WorkspaceSnapshot; 
/**
 * (project name, change lines); empty lines list = unchanged member.
 */
deltas: SnapshotDelta[]; clean: boolean }
/**
 * Item delivered on a patch subscription. `ResyncRequired` is terminal for
 * the subscription: the client must fetch a fresh snapshot and resubscribe.
 * A lagged subscriber is told to resync — never silently dropped patches.
 */
export type SubscriptionItem = { type: "patch"; patch: EnginePatch } | { type: "resyncRequired" }
/**
 * One tick: every running service Mast knows about, measured together so the
 * numbers can be summed and compared.
 */
export type UsageSample = { atUnixMs: number; 
/**
 * Cores the host has, so a client can say "2.3 of 8" rather than "2.3".
 */
hostCores: number; hostMemoryBytes: number; services: ServiceUsage[] }
export type WorkspaceId = string
export type WorkspaceMember = { project: ProjectId; 
/**
 * Projects that must be Ready before this one starts (workspace-level
 * `dependsOn`; compose-level `depends_on` stays inside each project).
 */
dependsOn: ProjectId[] }
export type WorkspaceSnapshot = { id: string; workspace: WorkspaceId; name: string; takenUnix: number; members: SnapshotMemberState[] }
export type WorkspaceSummary = { id: WorkspaceId; name: string; members: WorkspaceMember[]; 
/**
 * Derived from member project statuses.
 */
status: ProjectStatus; 
/**
 * Set when the dependency graph is unusable (e.g. a cycle).
 */
graphError: string | null; 
/**
 * Cross-project findings (M6): e.g. two members publishing the same
 * host port.
 */
warnings: string[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
