[package]
name = "mast-daemon"
version.workspace = true
edition.workspace = true

[[bin]]
name = "mast-daemon"
path = "src/main.rs"

[dependencies]
mast-contract.workspace = true
mast-engine.workspace = true
mast-project.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["net"] }
tracing.workspace = true

[dev-dependencies]
mast-client.workspace = true
mast-client-local.workspace = true
mast-client-ipc = { path = "../../sdk/mast-client-ipc" }
mast-docker = { workspace = true }
async-trait.workspace = true
tempfile = "3"
